fix(core): updated expandIcon to not show hover styles when active
medly/medly-components pull request #381
Opened 2021-08-12 14:10 UTC by iSyn

affects: @medly-components/core

### PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] Tests for the changes have been added (for bug fixes/features)
-   [ ] Docs have been added/updated (for bug fixes/features)

### PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Performance improves
-   [ ] Adding missing tests
-   [ ] Documentation content changes
-   [ ] Other... Please describe:

### What is the current behavior?

When hovering the expandIcon when its active, the icon color changes which is not the desired outcome.

## Fixes # (issue)

### What is the new behavior?

Now, when hovering the expandIcon while the custom search is active, the icon color doesn't change.

### Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### Additional context

Provide any additional context or screenshots about the feature PR.

2021-08-12 15:26 UTC, gmukul01 requested changes

2021-08-12 15:26 UTC, gmukul01 commented on packages/core/src/components/SearchBox/styles/icons.tsx
> +            `
Can you please create a separate style for this like we did for `customSearchActiveStyle`.

2021-08-23 18:40 UTC, jaredgiangrasso approved these changes

2021-08-23 18:40 UTC, jaredgiangrasso commented on packages/core/src/components/SearchBox/SearchBox.styled.tsx
> +    border-width: 2px;
```suggestion
    border-width: .2rem;
```

2021-08-27 02:25 UTC, merged