AM | docs(.md) content_changes
medly/medly-components pull request #588
Opened 2022-02-16 10:46 UTC by Annaleah123

### PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] Tests for the changes have been added (for bug fixes/features)
-   [x] Docs have been added/updated (for bug fixes/features)

### PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Performance improves
-   [ ] Adding missing tests
-   [x] Documentation content changes
-   [ ] Other... Please describe:

### What is the current behavior?

## Fixes # (issue)

### What is the new behavior?

### Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### Additional context

Provide any additional context or screenshots about the feature PR.

2022-02-25 11:28 UTC, abhishekashyap requested changes

2022-02-25 11:28 UTC, abhishekashyap commented on packages/core/src/components/Chip/Chip.stories.mdx
> +Use the basic chip prop as mentioned below:
```suggestion
Use the `Chip` as mentioned below:
```

2022-03-08 09:42 UTC, gmukul01 requested changes

2022-03-12 08:03 UTC, gmukul01 requested changes

2022-03-15 07:13 UTC, gmukul01 approved these changes

2022-03-15 07:14 UTC, abhishekashyap approved these changes

2022-03-15 10:01 UTC, merged