Core dp db dw fi
medly/medly-components pull request #594
Opened 2022-02-23 09:35 UTC by Annaleah123

### PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] Tests for the changes have been added (for bug fixes/features)
-   [x] Docs have been added/updated (for bug fixes/features)

### PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Performance improves
-   [ ] Adding missing tests
-   [x] Documentation content changes
-   [ ] Other... Please describe:

### What is the current behavior?

## Fixes # (issue)

### What is the new behavior?

### Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### Additional context

Provide any additional context or screenshots about the feature PR.

2022-02-23 09:41 UTC, wsameer commented on packages/core/src/components/FileInput/types.ts
> +    /** To use as per requirement in any form */
@Annaleah123  we could rephrase this as, "Use to make the input field mandatory while filing the form"

2022-02-25 09:56 UTC, abhishekashyap requested changes

2022-02-25 09:56 UTC, abhishekashyap commented on packages/core/src/components/DatePicker/DatePicker.stories.mdx
> +The DatePicker allows you to select a date through input text or using a calendar dialog.
```suggestion
The `DatePicker` allows you to select a date through input text or using a calendar dialog. 
```

2022-02-25 11:27 UTC, abhishekashyap commented on packages/core/src/components/DialogBox/DialogBox.stories.mdx
> +Dialog boxes are windows that appear in front of app content to give critical information, request a decision, or involve multiple tasks.  It consists of a Header, Content, and Action.
```suggestion
`DialogBox` are windows that appear in front of app content to give critical information, request a decision, or involve multiple tasks.  It consists of a Header, Content, and Action.
```

2022-02-25 11:54 UTC, gmukul01 requested changes

2022-02-25 11:54 UTC, gmukul01 commented on packages/core/src/components/DatePicker/DatePicker.stories.mdx
> +Handle the state as follows:
We should inform the user that `Its a controlled component`

2022-02-25 11:54 UTC, gmukul01 commented on packages/core/src/components/DatePicker/DatePicker.stories.mdx
> +3. The provision to enter the date manually is applicable.
I don't think `applicable` is a correct word over here

2022-02-25 11:54 UTC, gmukul01 commented on packages/core/src/components/DialogBox/DialogBox.stories.mdx
> +3. If the `shouldCloseOnOutsideClick` prop is selected, then dialog box will close on clicking outside the dialog box.
I think `selected` is not the right word over here, we can use `provided` or `set true`

2022-02-25 11:54 UTC, gmukul01 commented on packages/core/src/components/Drawer/Drawer.stories.mdx
> +A `Drawer` component provides access to locations in your application. It is anchored to the left or right edge of the screen. It consists of a Header, Content, and Footer.
`A Drawer component provides access to locations in your application.` This is not correct.

2022-02-25 11:54 UTC, gmukul01 commented on packages/core/src/components/Drawer/Drawer.stories.mdx
> +> Note: To view a complete description of the code click [here](https://github.com/medly/medly-components/blob/master/packages/core/src/components/Drawer/Drawer.stories.tsx)
its not the description, its the code itself

2022-02-25 11:54 UTC, gmukul01 commented on packages/core/src/components/FileInput/FileInput.stories.mdx
> +The `FileInput` component enables uploading files from the local storage to the server via the File API. As its value is read-only, it is an uncontrolled component.
We can just keep `The FileInput component enables uploading files from the local storage.`

2022-03-12 04:31 UTC, gmukul01 requested changes

2022-03-12 04:31 UTC, gmukul01 commented on packages/core/src/components/DatePicker/DatePicker.stories.mdx
> +1. Select the calendar icon inside the DatePicker component to open the calendar.
These three are not steps, they are individual statements. Also instead of using `select` word we should use `click`.

2022-03-15 06:25 UTC, merged