AM | docs (.mdx) content change: CORE_TT-INPUT-LABEL-LINK
medly/medly-components pull request #595
Opened 2022-02-23 13:13 UTC by Annaleah123

### PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] Tests for the changes have been added (for bug fixes/features)
-   [x] Docs have been added/updated (for bug fixes/features)

### PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Performance improves
-   [ ] Adding missing tests
-   [x] Documentation content changes
-   [ ] Other... Please describe:

### What is the current behavior?

## Fixes # (issue)

### What is the new behavior?

### Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### Additional context

Provide any additional context or screenshots about the feature PR.

2022-02-25 09:50 UTC, abhishekashyap requested changes

2022-02-25 09:50 UTC, abhishekashyap commented on packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.mdx
> +The HelperAndErrorTextTooltip displays informative text when you hover over or tap an element. When activated, it displays a text label identifying an element, such as a description of its function.
```suggestion
The `HelperAndErrorTextTooltip` displays informative text when you hover over or tap an element. When activated, it displays a text label identifying an element, such as a description of its function.
```

2022-02-25 09:50 UTC, abhishekashyap commented on packages/core/src/components/Input/Input.stories.mdx
> +The Input component allows you to get user input in a text field.
```suggestion
The `Input` component allows you to get user input in a text field. 
```

2022-02-25 09:50 UTC, abhishekashyap commented on packages/core/src/components/Label/Label.stories.mdx
> +The Label component lets you add captions to any element in your project. You can click or tap the label to activate the associated element.
```suggestion
The `Label` component lets you add captions to any element in your project. You can click or tap the label to activate the associated element.
```

2022-02-25 09:50 UTC, abhishekashyap commented on packages/core/src/components/Link/Link.stories.mdx
> +The Link component creates links primarily used for navigation. It semantically renders the anchor tag.
```suggestion
The `Link` component creates links primarily used for navigation. It semantically renders the anchor tag.
```

2022-02-25 11:58 UTC, gmukul01 requested changes

2022-02-25 11:58 UTC, gmukul01 commented on packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.mdx
> +The `HelperAndErrorTextTooltip` displays informative text when you hover over or tap an element. When activated, it displays a text label identifying an element, such as a description of its function
We can simply keep `The HelperAndErrorTextTooltip displays informative text when you hover over or tap an element.`

2022-02-25 11:58 UTC, gmukul01 commented on packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.mdx
> +The helper prop provides feedback about an error.
There is no helper prop. Please remove this Prop

2022-03-12 04:25 UTC, gmukul01 approved these changes

2022-03-12 04:55 UTC, merged