Core list modal pag po
medly/medly-components pull request #596
Opened 2022-02-25 11:40 UTC by Annaleah123

### PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] Tests for the changes have been added (for bug fixes/features)
-   [x] Docs have been added/updated (for bug fixes/features)

### PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Performance improves
-   [ ] Adding missing tests
-   [x] Documentation content changes
-   [ ] Other... Please describe:

### What is the current behavior?

## Fixes # (issue)

### What is the new behavior?

### Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### Additional context

Provide any additional context or screenshots about the feature PR.

2022-02-25 12:02 UTC, abhishekashyap commented on packages/core/src/components/Modal/types.ts
> +    /** Set it true to close the modal when clicking outside the popup */
```suggestion
    /** Set it true to close the modal when clicked outside the modal */
```

2022-03-07 15:43 UTC, gmukul01 requested changes

2022-03-07 15:43 UTC, gmukul01 commented on packages/core/src/components/Modal/Modal.stories.mdx
> +The `Modal` components are separate windows within an application that are mostly overlaid on the primary window. The contents behind a modal dialog are inert, meaning you cannot interact with the co
We should change it to `component is separate windows within an application that is overlaid on the primary window`

2022-03-07 15:43 UTC, gmukul01 commented on packages/core/src/components/Modal/Modal.stories.mdx
> +The Modal component supports keyboard navigation when in focus. You can use the Esc key to close the modal.
Could we please add the table back to maintain the consistency across the components.

2022-03-07 15:43 UTC, gmukul01 commented on packages/core/src/components/Popover/Popover.stories.mdx
> +Use the Popover Context type as mentioned below:
The below type is just for information not for use.

2022-03-12 04:21 UTC, gmukul01 approved these changes
LGTM

2022-03-12 04:55 UTC, merged