feat(core): update modal styling and behavior
medly/medly-components pull request #676
Opened 2022-06-24 13:10 UTC by nicu

affects: @medly-components/core

Update modal styling and fixed some of the bugs related to showing/hiding the shadow for content
overflow as well as header's fixed position on mobile devices.

# PR Checklist

## Description
Applied the changes from: https://medlypharmacy.atlassian.net/browse/WAT-689

- Desktop/Tablet: Reduce the outer padding from 48px to 32px.
- Mobile padding has some slight adjustments as well. Refer to Figma for the size differences.
- When scrolling the modal, the top and bottom portions reduce in height according to Figma across all devices.
- There will be 3 default sizes for the modal, but the modal should still be customizable to any width.

Designs: https://www.figma.com/file/aDwIJBirc228CKOVNZxCy9/New-B2C-Library?node-id=1303%3A2546

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes and API changes)
- [ ] Build changes
- [ ] CI changes
- [ ] Document content changes
- [ ] Performance improvement
- [ ] Add missing tests
- [x] Others (please describe)
Visual updates

## How has this been tested?
Manually

## Fixes [WAT-689](https://medlypharmacy.atlassian.net/browse/WAT-689)

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [x] I have commented my code, particularly in hard-to-understand areas

- [ ] I have made corresponding changes to the documentation

- [x] My changes generate no new warnings

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] New and existing unit tests pass locally with my changes

- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-28 10:06 UTC, gmukul01 requested changes

2022-06-28 10:06 UTC, gmukul01 commented on packages/core/src/components/Modal/Content/Content.styled.tsx
> +    /* overflow: ${({ overflowVisible }) => overflowVisible && `visible`}; */
Could we please remove this commented code ?

2022-06-28 10:06 UTC, gmukul01 commented on packages/core/src/components/Modal/Popup/Popup.styled.tsx
> +        /* padding: ${({ theme }) => `${theme.spacing.M2}`}; */
Could we please remove this commented code ?

2022-06-28 13:32 UTC, abhishekashyap requested changes

2022-06-28 13:32 UTC, abhishekashyap commented on packages/core/src/components/Modal/Content/Content.styled.tsx
> +        @media (min-width: 768px) and (max-height: 700px) {
Can we do something like so it is in sync with the theme:

```ts
${({ theme }) => media(`${breakpoints(theme.breakpoints).up('M')} and (max-height: 700px)`)`
        // Your css here
`}
```

2022-06-28 13:32 UTC, abhishekashyap commented on packages/core/src/components/Modal/Actions/Actions.styled.tsx
> +    @media (max-width: 767px) {
Similarly for this:

```ts
${({ theme }) => media(breakpoints(theme.breakpoints).down('S'))`
        // Your css here
`}
```

2022-06-29 06:10 UTC, PulkitBanta approved these changes
LGTM

2022-06-29 06:21 UTC, abhishekashyap approved these changes

2022-06-29 06:38 UTC, gmukul01 approved these changes

2022-06-30 11:44 UTC, merged